### ISSUE TITLE
Broken image + name change

### ISSUE THREAD

**Issue by notwaving** [WeRockTech/awesome-tech-communities#10]
1. The image for **Unfold Inclusion in UK XR** is broken and I can see where it _should_ be when looking at the html in Chrome dev tools; but ndex.html in your repo doesn’t match up with it, and I'm not familiar with Angular.

![screen shot 2017-10-04 at 22 10 53](https://user-images.githubusercontent.com/20457311/31200096-82d4ad80-a951-11e7-96fe-b34a83821b7b.png)

I noticed you're linking images from Meetup, here's Unfold's: https://secure.meetupstatic.com/photos/event/d/f/2/0/highres_460377120.jpeg

2. I think their name might have changed to **Unfold UK** https://www.meetup.com/unfolduk/ Happy to amend if I can get into the source code.

**Comment by eddiejaoude** [comment]
Thanks for spotting 👍 . 

I am happy to help support with the fix 🤓 ....

The **data** is not in the source code but managed by a `json` data file. Here is a [link](https://github.com/WeRockTech/awesome-tech-communities/blob/master/data/communities.json#L108) to the file and the object for this entry, which looks like this...

```json
{
    "name": "Unfold Inclusion in UK XR",
    "description": "Powering inclusion in immersive tech. We're a support network that actively promotes & champions the inclusion of all underrepresented groups in the VR, AR and MR space. Formerly Women in VR UK",
    "url": "https://www.facebook.com/groups/unfolduk/",
    "logo": "https://scontent-otp1-1.xx.fbcdn.net/v/t1.0-9/18485911_10156375476758532_7563742107552031879_n.jpg?oh=072724ab61f485af2fb601d40a0ae0b6&oe=59B3E6A4",
    "social": [
      {
        "name": "twitter",
        "url": "http://twitter.com/UnfoldWomen"
      }
    ],
    "codeOfConduct": "",
    "levels": ["beginner", "intermediate", "advanced"],
    "tags": ["VR", "AR", "Women", "Gender"]
  }
```

Here are the docs for in the [README.md:UpdateData](https://github.com/WeRockTech/awesome-tech-communities#update), but probably need some *TLC*, please can you let me know what is missing in the docs to help onboard more people.

Thanks 😄

**Comment by notwaving** [comment]
Thanks for guiding me through this. I'm blaming late night brain for not a) seemingly opening every file _except_ `communities.json`; b) scrolling down the page to read the rest of the README...

It was all very easy to follow!

Regarding the actual issue:
1. Is complete and PR'd.
2. I checked them on Facebook and they're listed under this long version of their name, so no change has been made.

**Comment by eddiejaoude** [comment]
Thank you 👍 . PR merged 🤓
